name: Deploy Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

# https://bishenderson.atlassian.net/wiki/spaces/MFS/pages/4718644/Deployment+Security
permissions:
  id-token: write
  contents: read
  
jobs:
  deploy_dev:
    name: Deploy to Development
    env:
      DEPLOY_ENV: DEV
      DEPLOY_BRANCH: main
    uses: ./.github/workflows/deploy.yml

  deploy_staging:
    name: Deploy to Staging
    env:
      DEPLOY_ENV: TEST
      DEPLOY_BRANCH: main
    uses: ./.github/workflows/deploy.yml
      
