on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

# https://bishenderson.atlassian.net/wiki/spaces/MFS/pages/4718644/Deployment+Security
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/azure-dev-cli-apps:latest
    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
        
      - name: ContractImport Functions - Install dependencies 
        run: |
          cd src/ContractImport
          dotnet restore 
        shell: pwsh
      
      - name: ContractImport Functions - Build
        run: |
          cd src/ContractImport
          dotnet build --configuration Release --no-restore 
    
      - name: ContractImport Functions - Test
        run: |
          cd src/ContractImport
          dotnet test --no-restore --verbosity normal

      - name: Log in with Azure (Federated Credentials)
        run: |
           azd auth login `
             --client-id "$Env:AZURE_CLIENT_ID" `
             --federated-credential-provider "github" `
             --tenant-id "$Env:AZURE_TENANT_ID"
        shell: pwsh

      - name: Azure Dev Configuration
        run: azd config set alpha.terraform on 

      - name: Azure Dev Provision
        run: azd provision --no-prompt
        env:
          AZURE_ENV_NAME: ${{ secrets.AZURE_ENV_NAME }}
          AZURE_LOCATION: ${{ secrets.AZURE_LOCATION }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # - name: Azure Dev Deploy
      #   run: azd deploy --no-prompt
      #   env:
      #     AZURE_ENV_NAME: ${{ secrets.AZURE_ENV_NAME }}
      #     AZURE_LOCATION: ${{ secrets.AZURE_LOCATION }}
      #     AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
