name: Build

on:
  # support calling this workflow from other workflows
  # https://docs.github.com/en/actions/learn-github-actions/reusing-workflows#creating-a-reusable-workflow
  workflow_call:
  # support running this workflow on push events
  # https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#onpushpull_requestbranchestags
  push:
    branches-ignore: main

jobs:
  build:
    # https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-latest

    # https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idsteps
    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        # 2.4.0 was the latest at the time of writing
        uses: actions/checkout@v2.4.0
        
        
      # upload the artifact for use in either CD
      # here, the 'dist' directory is compressed and uploaded to GitHub asset storage as 'build-artifact'
      #- name: Upload artifact
      #  # https://github.com/actions/upload-artifact
      #  uses: actions/upload-artifact@v2
      #  with:
      #    # the name to save the compressed asset as
      #    name: build-artifact
      #    # the directory or file to upload. adapt to your needs
      #    path: dist
      #   # the artifact is only needed for the duration of the build-deploy workflow
      #   # adapt to your needs
      #   # https://github.com/actions/upload-artifact#retention-period
      #   retention-days: 1
