name: My Workflow

on: [push]

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
    - name: Set environment variable
      run: |
        # Set the environment variable
        Set-Variable -Name MY_VARIABLE -Value "my value" -Scope 'process'

        # Display the environment variable value
        Write-Host "MY_VARIABLE = $env:MY_VARIABLE"

    - name: Use environment variable in next step
      run: |
        # Access the environment variable set in the previous step
        Write-Host "MY_VARIABLE = $env:MY_VARIABLE"
